# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dlist, hspec, HUnit, text, time, unorderedContainers
, vector
}:

cabal.mkDerivation (self: {
  pname = "data-default-generics";
  version = "0.3";
  sha256 = "0asjirn324ixyzkf5vhanyf7q9aj9zh693m55qln7dx3vdayn1yv";
  buildDepends = [ dlist text time unorderedContainers vector ];
  testDepends = [
    dlist hspec HUnit text time unorderedContainers vector
  ];
  meta = {
    description = "A class for types with a default value";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
