# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, aesonPretty, attoparsec, Cabal, deepseq, filepath
, ghcMod, ghcPaths, haddock, haskellSrcExts, hdocs, HTTP
, MonadCatchIOTransformers, monadLoops, mtl, network, regexpr, text
, time, transformers, unorderedContainers, vector
}:

cabal.mkDerivation (self: {
  pname = "hsdev";
  version = "0.1.0.1";
  sha256 = "1lc1mrnhn6qngh3vm0wbar78j933s4l45jkg2657yggfbwb4n681";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    aeson aesonPretty attoparsec Cabal deepseq filepath ghcMod ghcPaths
    haddock haskellSrcExts hdocs HTTP MonadCatchIOTransformers
    monadLoops mtl network regexpr text time transformers
    unorderedContainers vector
  ];
  meta = {
    homepage = "https://github.com/mvoidex/hsdev";
    description = "Haskell development library and tool with support of autocompletion, symbol info, go to declaration, find references etc";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
